# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Include additional configuration files
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Telegram Bot Configuration
telegram_bot:
  - platform: polling
    api_key: "<tg api key>"
    allowed_chat_ids:
      - id1
      - id2

# Notification via Telegram
notify:
  - platform: telegram
    name: "sreejith"
    chat_id: id1
  - platform: telegram
    name: "lia"
    chat_id: id2

# Command Line Sensors
command_line:
  - sensor:
      name: Moisture Sensor
      unique_id: e637b1b7-daa6-4391-bbc6-94666dfe98a4
      command: python3 /config/scripts/indoor_soil_moisture_info.py
      scan_interval: 600  # Update every 10 minutes
      value_template: '{{ value_json["Sns1"] }}'
      json_attributes:
        - Sns1
        - Sns2
        - Sns3
        - Sns4
  - sensor:
      name: Air Quality Sensor
      unique_id: f4b828ff-6151-440b-b35e-d9e7a64aee57
      command: python3 /config/scripts/air_quality.py
      scan_interval: 10800  # Update every 3 hours
      value_template: '{{ value_json["aqi"] }}'
      json_attributes:
        - co
        - no
        - no2
        - o3
        - so2
        - pm2_5
        - pm10
        - nh3
        - quality_desc

# Shell Command for Pump Control
shell_command:
  run_pump_request: "python3 /config/scripts/pump.py {{ pump_name }}"

# Template Sensors
template:
  - sensor:
      - name: "Time of Day"
        state: >
          {% set hour = now().hour %}
          {% if 5 <= hour < 12 %} Morning
          {% elif 12 <= hour < 17 %} Afternoon
          {% elif 17 <= hour < 21 %} Evening
          {% else %} Night
          {% endif %}
        icon: >
          {% if 5 <= now().hour < 12 %} mdi:weather-sunset-up
          {% elif 12 <= now().hour < 17 %} mdi:weather-sunny
          {% elif 17 <= now().hour < 21 %} mdi:weather-sunset-down
          {% else %} mdi:weather-night
          {% endif %}
      - name: "Destination address"
        state: >
          {%- if is_state("input_select.destination", "Home") -%}
            4200 Alderwood Mall Blvd, Lynnwood, WA 98036, USA
          {%- elif is_state("input_select.destination", "Work") -%}
            Two Chairs, 2101 4th Ave #1850, Seattle, WA 98121
          {%- elif is_state("input_select.destination", "MyLoc") -%}
            device_tracker.myphone
          {%- else -%}
            Unknown
          {%- endif %}

# Input Select for Destination
input_select:
  destination:
    name: Destination
    options:
      - Home
      - Work
      - MyLoc

# Apache Kafka Configuration
apache_kafka:
  ip_address: localhost
  port: 9092
  topic: home_assistant_1
